# Generated by Django 6.0.1 on 2026-02-09 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_adminprofile_ambassadorprofile_customerprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ambassadorprofile",
            name="commission_rate",
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=5),
        ),
        migrations.AlterField(
            model_name="ambassadorprofile",
            name="referral_code",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
